on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run test lane
        run: bundle exec fastlane android fuck

      - name: Echo output env var
        run: echo "$apkPath"
